import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <main className="m-4 md:m-20 p-4 md:p-20 bg-slate-700 rounded-sm">
          {children}
        </main>
      </body>
    </html>
  );
}
